---
Name: damnfineuploader
---
Codem\DamnFineUploader\DamnFineUploaderField:
  signing_key : ''
  allow_delete : true
  unpublish_after_upload : true
  # config for the frontend lib
  implementation:
    autoUpload: true
    maxConnections: 3
    multiple: true
    warnBeforeUnload: true
    form:
      interceptSubmit: false
    validation:
      itemLimit: 3
      sizeLimit: 5242880
      image:
        maxWidth : 2560
        maxHeight : 1440
    debug: true
    retry:
      enableAuto: false
    deleteFile:
      forceConfirm: true
      method: 'POST'
    scaling:
      defaultQuality: 90
