---
Name: damnfineuploader
---
Codem\DamnFineUploader\DamnFineUploaderField:
  signing_key : ''
  allow_delete : true
  # config for the frontend lib
  implementation:
    validation:
      acceptFiles: 'image/jpg,image/jpeg,image/png,image/webp'
      itemLimit: 3
      sizeLimit: 5242880
      image:
        maxWidth : 2560
        maxHeight : 1440
    debug: false
    deleteFile:
      forceConfirm: true
      method: 'POST'
Codem\DamnFineUploader\EditableUploadField:
  # migration_1 is fineuploader deprecation
  run_migration_1: false
  run_migration_manymanyhasmany: false
  run_migration_allowedmimetypedeprecation: false
