---
Name: damnfineuploader
---
Codem\DamnFineUploader\FineUploaderCoreField:
  # config for fineuploader
  signing_key : 'SAMPLEONLY'
  fineuploader:
    autoUpload: true
    interceptSubmit: false
    validation:
      itemLimit: 3
      sizeLimit: 5242880
    debug: false
    retry:
      enableAuto: false
    deleteFile:
      enabled: false
