---
Name: damnfineuploader
---
Codem\DamnFineUploader\FineUploaderCoreField:
  # config for fineuploader
  signing_key : 'SAMPLEONLY'
  fineuploader:
    autoUpload: true
    maxConnections: 3
    multiple: true
    warnBeforeUnload: true
    form:
      interceptSubmit: false
    validation:
      itemLimit: 3
      sizeLimit: 5242880
      image:
        maxHeight : 1440
        maxWidth : 2560
    debug: true
    retry:
      enableAuto: false
    deleteFile:
      enabled: false
    scaling:
      defaultQuality: 90
