---
Name: damnfineuploader
---
Codem\DamnFineUploader\DamnFineUploaderField:
  signing_key : ''
  allow_delete : true
  # config for the frontend lib
  implementation:
    validation:
      acceptFiles: 'image/jpg,image/gif,image/png,image/webp,image/jpeg'
      itemLimit: 3
      sizeLimit: 5242880
      image:
        maxWidth : 2560
        maxHeight : 1440
    debug: false
    deleteFile:
      forceConfirm: true
      method: 'POST'
